// Builds src/data/pokedex.js from pokemondb.net national dex table (default form of each species).
// Usage: node tools/build-pokedex.mjs
import { writeFile } from 'node:fs/promises';

const html = await (await fetch('https://pokemondb.net/pokedex/all')).text();
const body = html.slice(html.indexOf('<tbody>'), html.indexOf('</tbody>'));
const rows = body.split('<tr>').slice(1);
const seen = new Set();
const out = [];
for (const r of rows) {
  const num = Number(r.match(/data-sort-value="(\d+)"/)?.[1]);
  const name = r.match(/class="ent-name"[^>]*>([^<]+)<\/a>/)?.[1];
  const slug = r.match(/href="\/pokedex\/([^"]+)"/)?.[1];
  if (!num || !name || !slug) continue;
  // The first row for each dex number is the default form; later rows (Mega, regional, …) are skipped.
  if (seen.has(num)) continue;
  seen.add(num);
  const types = [...r.matchAll(/class="type-icon type-(\w+)"/g)].map((m) => m[1]);
  const nums = [...r.matchAll(/<td class="cell-num">(\d+)<\/td>/g)].map((m) => Number(m[1]));
  if (nums.length !== 6) throw new Error(`bad row for ${name}`);
  out.push([num, name.replace(/&#039;/g, "'").replace(/&eacute;/g, 'é'), slug, types.join('/'), ...nums]);
}
const src = `// Generated by tools/build-pokedex.mjs from pokemondb.net/pokedex/all. Base forms only.
// Row: [dex number, name, slug, types, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed]
const ROWS = ${JSON.stringify(out).replace(/\],\[/g, '],\n[')};

export const POKEDEX = ROWS.map(([num, name, slug, types, hp, attack, defense, spAttack, spDefense, speed]) => ({
  num, name, slug, types: types.split('/'),
  stats: { hp, attack, defense, spAttack, spDefense, speed },
}));

const bySlug = new Map(POKEDEX.map((p) => [p.slug, p]));
export const getPokemon = (slug) => bySlug.get(slug) ?? null;

// Pokémon HOME artwork, hotlinked from pokemondb.net (size: 'normal' ≈ 512px or '1x' ≈ 128px).
export const spriteUrl = (slug, size = '1x') =>
  size === '1x' ? \`https://img.pokemondb.net/sprites/home/normal/1x/\${slug}.png\` : \`https://img.pokemondb.net/sprites/home/normal/\${slug}.png\`;
`;
await writeFile(new URL('../src/data/pokedex.js', import.meta.url), src);
console.log(`${out.length} Pokémon written`);
